### PR TITLE
modify about page content

### PR DESCRIPTION
**Pull request by IsthisSid**
The About page content is complete.

**Please note that I had to comment out lines 14 to 26, as well as the imported util, in RowImages.jsx file in order to use the RowImages component on the About Page. The desired effect is to only display the images (no heading, text, or icon).** 

Please review if these lines should be deleted.

### CODE REVIEW

**Review by codeTrackLift — COMMENTED** [review]
I'm not sure this is the best solution here.  Does this affect RowImages on other pages?

**Review by codeTrackLift — CHANGES_REQUESTED** [review]
Screen Shot 2022-10-11 at 5 43 43 PM

Please revert changes to RowImages and update About.jsx based on the screenshot above.  This should produce the desired affect without breaking the row component.

**Comment by IsthisSid** [comment]
I understand your concern. I should clarify that DK specifically requested the particular style (RowImages to be a row of 3 images only). The RowImages component would be used on the About and Gallery Pages.

**Review by codeTrackLift — APPROVED** [review]
👍

**Pull request merged**
